### PR TITLE
Rebased issaquah issues processing

### PR DESCRIPTION
**Pull request by ericniebler**
Merge the fixes that were approved in Issaquah but that didn't make it into the PDTS.

### CODE REVIEW

**Comment by ericniebler** [comment]
> I don't want any confusion over "speculative" work vs. what is the actual working paper.

How is this speculative? It's all been approved by full committee.

**Comment by CaseyCarter** [comment]
> How is this speculative? It's all been approved by full committee.

These are issue resolutions that have been approved by LWG but not yet moved and approved by WG21 in full plenary.

**Comment by ericniebler** [comment]
> not yet moved and approved by WG21 in full plenary.

\<sigh\>

**Comment by ericniebler** [comment]
These have now been moved in plenary, right? OK to merge?

**Comment by CaseyCarter** [comment]
I'm planning to make one more pass through the prs and edits to make sure they agree before merging. That will be tomorrow, I'm still stuck in kona. (Flight was delayed by eighteen hours)

**Pull request merged**
