### PR TITLE
Patch for #354 and #357

### PR DESCRIPTION
**Pull request by cjdb**

### CODE REVIEW

**Comment by ericniebler** [comment]
Please rebase on master to remove all these merge commits.

```
git checkout jp-nb
git fetch
git rebase origin/master
(fix any merge conflicts)
git push origin +jp-nb
```

**Comment by cjdb** [comment]
> Please rebase on master to remove all these merge commits.

Thanks!

**Comment by CaseyCarter** [comment]
Could you split these into separate PRs? Also, the `Range` concept moved into `ranges.tex`.

**Comment by CaseyCarter** [comment]
I've stolen #354 after glancing at the wording and realizing that the required expression `ranges::begin(t)` needs a `// not necessarily equality-preserving` comment since the textual specification makes it clear that `begin` need only be e-p for forward ranges.

**Comment by CaseyCarter** [comment]
...and I've stolen #357 as well since the PR is four words long.

**Pull request closed without merging**
