### PR TITLE
Reorder requirements in concept Iterator

### PR DESCRIPTION
**Pull request by cjdb**
Patch for issue #331.

### CODE REVIEW

**Comment by cjdb** [comment]
Will refer to issues in commit messages from now on (apparently GitHub acknowledges them).

**Comment by ericniebler** [comment]
This resolution was approved in Kona, but it's not editorial. I can't merge this until the resolution is moved in plenary in Toronto, 4 months from now.

**Comment by CaseyCarter** [comment]
> Will refer to issues in commit messages from now on (apparently GitHub acknowledges them).

Yes, and if you use the form "Fixes #331" or "Closes #331" in the commit message, github will automatically close the referenced issue when the PR is merged.

**Comment by CaseyCarter** [comment]
This needs to be rebased and translated into the only-variable-concepts universe.

**Comment by CaseyCarter** [comment]
Superseded by #490.

**Pull request closed without merging**
