### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by CaseyCarter**

### CODE REVIEW

**Comment by ericniebler** [comment]
Shall I merge these changes into my PR to keep the history clean?

**Comment by CaseyCarter** [comment]
> Shall I merge these changes into my PR to keep the history clean?

I'm not concerned about the history - these are very minor.

**Comment by ericniebler** [comment]
Darn phone UI didn't show me the base Rev so I applied I in the wrong order. These changes are lost. Can you resubmit against master?

**Comment by CaseyCarter** [comment]
Fixed in 1836cccdca8af0f81004f7eccc0ccb0633238147.

**Pull request merged**
