### PR TITLE
strip all newtxt and oldtxt from algorithms.tex

### PR DESCRIPTION
**Pull request by ericniebler**

### CODE REVIEW

**Comment by ericniebler** [comment]
This represents a complete reset of the markup on algorithms.tex. I'm requesting to merge it into a new "markup-reset" branch where we can collect and resolve all our markup-related changes. When we're done, we can do one final squash-and-merge of markup-reset into master.

**Comment by CaseyCarter** [comment]
> 1,019 additions, 1,289 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

Grrr.

>  I'm requesting to merge it into a new "markup-reset" branch where we can collect and resolve all our markup-related changes. When we're done, we can do one final squash-and-merge of markup-reset into master.

I agree this is a reasonable plan.

**Comment by ericniebler** [comment]
> Grrr.

Yeah, sorry. I felt doing it piecemeal was going to increase my chances of making a mistake so I did the whole thing in one epic marathon morning session. Now I need to rest my eyes. FWIW, Github Desktop works well for this.

**Comment by CaseyCarter** [comment]
I probably won't get to reviewing this until late tonight / early tomorrow, which I'm afraid will interfere with you and Chris maintaining workflow. Feel free to go ahead and merge and I'll catch up on review as I can - certainly before we land all of the markup changes on master.

**Pull request merged**
